### ISSUE TITLE
Preview sync: white text on yellow background

### ISSUE THREAD

**Issue by hlamer** [bjones1/enki#34]
![white-on-yellow](https://cloud.githubusercontent.com/assets/419720/6440651/49b32aaa-c0f0-11e4-8dfd-f291e5eead90.png)

When preview sync is active, selected line on the Preview dock is drawn as white text on yellow background.
It could depend on desktop UI settings.

**Comment by bjones1** [comment]
Hmmm. That is ugly. Let me take a look. As you say, this is probably desktop-UI dependent (aargh).

**Comment by bjones1** [comment]
This looks fine on Windows 7.

**Comment by bjones1** [comment]
Looking a bit, the default Windows palette (taken from a Qt Designer screen shot) is:

![windows_palette](https://cloud.githubusercontent.com/assets/2125584/6605759/5b1d3c2e-c800-11e4-9541-f225a38fbe64.png)

In contrast, the default Linux palette (Fedora 21) is:
![linux_palette](https://cloud.githubusercontent.com/assets/2125584/6605767/6b231788-c800-11e4-843f-30fa290152bf.png)

Note that the inactive HighlightedText colors are different, which causes the problem.
