### ISSUE TITLE
Separate tab for sphinx project

### ISSUE THREAD

**Issue by hlamer** [bjones1/enki#38]
We've already discussed it, but now I can't find the discussion, and don't remember what where my and your opinion.

How about moving sphinx settings from "Literate programming" to separate tab "Sphinx"? Sphinx preview might be used not only for literate programming, but also to write docs, which don't consist any code.

**Comment by bjones1** [comment]
I see some discussion at pull request #28 and also at my pull request [239](https://github.com/hlamer/enki/pull/239). As you say, Sphinx can be used as a part of the literate programming flow, but also completely separately from the literate programming flow. So, I'll add a Sphinx tab, then refer to it on the Literate Programming tab.

**Comment by bjones1** [comment]
Looking at this again, splitting these two would create a setting panel with one checkbox (CodeChat, under literate programming). I think this fine granularity makes the settings dialog harder to use (see, e.g., https://github.com/hlamer/enki/issues/273). So, I think these should be kept together, but perhaps the category renamed -- "Document generation,\n literate programming"? (on separate lines).

**Comment by hlamer** [comment]
I still like 2 tabs. For me CodeChat and Sphinx is different functionality. There are many users who need only Sphinx and don't want to know what is CodeChat, and many uses who know only about CodeChat. So, why force this users to understand, what is written on the page?

CodeChat page is not empty. It contains some documentation, link to CodeChat page. You can add a hint, if CodeChat is correctly installed.

**Comment by bjones1** [comment]
Sounds good. Will do.

**Comment by bjones1** [comment]
Closed by merge.
