### ISSUE TITLE
Test crashes when tre is available

### ISSUE THREAD

**Issue by hlamer** [bjones1/enki#40]
The tests used to pass fine for me while I didn't have tre installed. Now when I run the tests with `run_tests.py`, I got output below.  If I run only `./test_approx_match.py` - all passes.
It seems like this depends on performance or on some modifications in global process environment.

Do the test pass for you if tre is available?

**Comment by bjones1** [comment]
I don't see an output log -- would you provide it? I have TRE installed on Windows, and it works. Which TRE -- the Linux-provided (non-unicode) or the manually-built one from my repo? What Linux?

**Comment by hlamer** [comment]
I have Linux Mint 16. Tre is manually build from your repo.
Log is in the next commentary.

**Comment by hlamer** [comment]
test_1 (test_base.TestInMainLoop) ... ok
test_1 (test_base.TestWaitForSignal) ... ok
test_10 (test_base.TestWaitForSignal) ... ok
test_11 (test_base.TestWaitForSignal) ... ok
test_2 (test_base.TestWaitForSignal) ... ok
test_3 (test_base.TestWaitForSignal) ... ok
test_4 (test_base.TestWaitForSignal) ... ok
test_5 (test_base.TestWaitForSignal) ... ok
test_7 (test_base.TestWaitForSignal) ... ok
test_8 (test_base.TestWaitForSignal) ... ok
test_9 (test_base.TestWaitForSignal) ... ok
test_sync1 (test_plugins.test_preview_sync.Test)
Test that web-to-text sync occurs on clicks to the web pane. ... ok
test_sync10 (test_plugins.test_preview_sync.Test) ... ok
test_sync11 (test_plugins.test_preview_sync.Test) ... ok
test_sync12 (test_plugins.test_preview_sync.Test)
Tables with an embedded image cause findText to fail. ... expected failure
test_sync13 (test_plugins.test_preview_sync.Test) ... ok
test_sync14 (test_plugins.test_preview_sync.Test) ... ok
test_sync15 (test_plugins.test_preview_sync.Test) ... ok
test_sync16 (test_plugins.test_preview_sync.Test)
Tables with column spans produce out-of-order text, so sync in some rows ... ok
test_sync17 (test_plugins.test_preview_sync.Test)
A failing case of the above test series. ... ok
test_sync18 (test_plugins.test_preview_sync.Test)
Verify that sync after the column span works. ... ok
test_sync19 (test_plugins.test_preview_sync.Test) ... ok
test_sync2 (test_plugins.test_preview_sync.Test)
Simulate a click after 'The pre' and check the resulting ``jsClick`` result. ... ok
test_sync20 (test_plugins.test_preview_sync.Test) ... ok
test_sync21 (test_plugins.test_preview_sync.Test) ... ok
test_sync22 (test_plugins.test_preview_sync.Test)
Prevent TRE from being imported. Make sure there are no exceptions. ... ok
test_sync23 (test_plugins.test_preview_sync.Test)
Import an old TRE that doesn't handle unicode. Make sure preview_sync ... ok
test_sync2a (test_plugins.test_preview_sync.Test)
TODO: simulate a click before the first letter. Select T, then move backwards using ... ok
test_sync3 (test_plugins.test_preview_sync.Test)
Same as above, but with the entire string. ... ok
test_sync4 (test_plugins.test_preview_sync.Test)
Test a click at the beginning of the string. ... ok
test_sync5 (test_plugins.test_preview_sync.Test)
Test a click at the middle of the string. ... ok
test_sync6 (test_plugins.test_preview_sync.Test)
Test a click at the end of the string. ... ok
test_sync7 (test_plugins.test_preview_sync.Test)
Test on an empty document. ... ok
test_sync8 (test_plugins.test_preview_sync.Test)
Test with javascript disabled. ... ok
test_sync9 (test_plugins.test_preview_sync.Test) ... ok
test_1 (test_plugins.test_workspace_commands.Test) ... ok
test_2 (test_plugins.test_workspace_commands.Test) ... ok
test_3 (test_plugins.test_workspace_commands.Test) ... ok
test_4 (test_plugins.test_workspace_commands.Test) ... ok
test_5 (test_plugins.test_workspace_commands.Test) ... ok
test_1 (test_plugins.test_import_fail.TestImportFail)
Make sure ImportFail causes an exception for a fail_name. ... ok
test_2 (test_plugins.test_import_fail.TestImportFail)
Make sure ImportFail causes an exception for multiple fail_names. ... ok
test_3 (test_plugins.test_import_fail.TestImportFail)
Make sure import of other modules works. ... ok
test_4 (test_plugins.test_import_fail.TestImportFail)
Check that reload isn't called if no modules are given. ... ok
test_5 (test_plugins.test_import_fail.TestImportFail)
Check that reload is called twice. ... ok
test_6 (test_plugins.test_import_fail.TestImportFail)
Check that reload is called in the correct context. ... ok
test_commonPrefix1 (test_plugins.test_preview.Test) ... ok
test_commonPrefix10 (test_plugins.test_preview.Test) ... skipped 'requires Windows'
test_commonPrefix10a (test_plugins.test_preview.Test) ... ok
test_commonPrefix11 (test_plugins.test_preview.Test)
Check that leading ../current_subdir will be removed after path ... ok
test_commonPrefix11a (test_plugins.test_preview.Test) ... ok
test_commonPrefix12 (test_plugins.test_preview.Test) ... skipped 'requires Windows'
test_commonPrefix12a (test_plugins.test_preview.Test) ... ok
test_commonPrefix13 (test_plugins.test_preview.Test) ... skipped 'requires Windows'
test_commonPrefix14 (test_plugins.test_preview.Test) ... ok
test_commonPrefix15 (test_plugins.test_preview.Test) ... ok
test_commonPrefix16 (test_plugins.test_preview.Test) ... ok
test_commonPrefix2 (test_plugins.test_preview.Test) ... ok
test_commonPrefix3 (test_plugins.test_preview.Test) ... ok
test_commonPrefix5 (test_plugins.test_preview.Test) ... skipped 'requires Windows'
test_commonPrefix6 (test_plugins.test_preview.Test) ... ok
test_commonPrefix7 (test_plugins.test_preview.Test) ... skipped 'requires Windows'
test_commonPrefix8 (test_plugins.test_preview.Test) ... ok
test_commonPrefix9 (test_plugins.test_preview.Test) ... skipped 'requires Windows'
test_commonPrefix9a (test_plugins.test_preview.Test) ... ok
test_copyTemplateFile1 (test_plugins.test_preview.Test) ... ok
test_copyTemplateFile2 (test_plugins.test_preview.Test) ... ok
test_copyTemplateFile2a (test_plugins.test_preview.Test) ... ok
test_copyTemplateFile3 (test_plugins.test_preview.Test) ... ok
test_copyTemplateFile3a (test_plugins.test_preview.Test) ... ok
test_copyTemplateFile4 (test_plugins.test_preview.Test) ... ok
test_copyTemplateFile5 (test_plugins.test_preview.Test) ... ok
test_emptyCodeChatDocument (test_plugins.test_preview.Test) ... ok
test_emptyDocument (test_plugins.test_preview.Test) ... ok
test_emptySphinxDocument (test_plugins.test_preview.Test) ... ok
test_getSphinxVersion1 (test_plugins.test_preview.Test)
Check that _getSphinxVersion raises an exception if the binary isn't ... ok
test_getSphinxVersion2 (test_plugins.test_preview.Test)
Check that _getSphinxVersion raises an exception if the Sphinx ... ok
test_getSphinxVersion3 (test_plugins.test_preview.Test)
Check that _getSphinxVersion raises an exception if the Sphinx ... ok
test_html (test_plugins.test_preview.Test) ... ok
test_logWindowSplitter1 (test_plugins.test_preview.Test)
Feature 1. Created files will have same default splitter size. ... ok
test_logWindowSplitter2 (test_plugins.test_preview.Test)
Feature 2. All build-with-error files' splitter size are connected. ... ok
test_logWindowSplitter3 (test_plugins.test_preview.Test)
Feature 3. Error free document will not affect other documents' ... ok
test_logWindowSplitter3a (test_plugins.test_preview.Test)
Feature 1,2,3. A combination of the above test cases. ... ok
test_logWindowSplitter4 (test_plugins.test_preview.Test)
User actively hide log window, Enki should be able to remember this. ... ok
test_markdown (test_plugins.test_preview.Test) ... ok
test_markdown_templates (test_plugins.test_preview.Test) ... ok
test_markdown_templates_help (test_plugins.test_preview.Test) ... ok
test_previewCheck1 (test_plugins.test_preview.Test)
If Enki is opened with CodeChat enabled, the preview dock should be ... ok
test_previewCheck10 (test_plugins.test_preview.Test)
Empty input should generate an empty log. ... ok
test_previewCheck11 (test_plugins.test_preview.Test)
Unicode should display correctly in log window too. ... ok
test_previewCheck12 (test_plugins.test_preview.Test) ... skipped "Unicode isn't presented in the log window"
test_previewCheck13 (test_plugins.test_preview.Test)
Test progress bar status (indefinitely) when building ... ok
test_previewCheck14 (test_plugins.test_preview.Test)
Check different progressbar color given different scenarios. ... ok
test_previewCheck15 (test_plugins.test_preview.Test) ... ok
test_previewCheck16 (test_plugins.test_preview.Test) ... ok
test_previewCheck17 (test_plugins.test_preview.Test)
A complex test case that tests both the log parser regexp and ... ok
test_previewCheck18 (test_plugins.test_preview.Test) ... ok
test_previewCheck19 (test_plugins.test_preview.Test) ... ok
test_previewCheck2 (test_plugins.test_preview.Test) ... ok
test_previewCheck20 (test_plugins.test_preview.Test) ... ok
test_previewCheck20a (test_plugins.test_preview.Test) ... ok
test_previewCheck21 (test_plugins.test_preview.Test) ... ok
test_previewCheck22 (test_plugins.test_preview.Test)
Assume codechat is not installed, render a .rst file using ... ok
test_previewCheck23 (test_plugins.test_preview.Test)
If the document is modified externally, then build on save will be ... ok
test_previewCheck2a (test_plugins.test_preview.Test) ... ok
test_previewCheck3 (test_plugins.test_preview.Test) ... ok
test_previewCheck3a (test_plugins.test_preview.Test) ... ok
test_previewCheck4 (test_plugins.test_preview.Test)
If Enki is opened without any configuration, the preview dock will ... ok
test_previewCheck5 (test_plugins.test_preview.Test) ... ok
test_previewCheck6 (test_plugins.test_preview.Test)
If an empty code file is passed to Enki, the CodeChat preview panel ... ok
test_previewCheck6a (test_plugins.test_preview.Test) ... ok
test_previewCheck7 (test_plugins.test_preview.Test)
Test that Unicode characters are handled properly. ... ok
test_previewCheck7a (test_plugins.test_preview.Test) ... ok
test_previewCheck8 (test_plugins.test_preview.Test)
Start with a short code file, make sure the preview window isn't ... ok
test_previewCheck8a (test_plugins.test_preview.Test) ... ok
test_previewCheck9 (test_plugins.test_preview.Test)
Uninterpretable reStructuredText syntax in source code will generate ... ok
test_previewCheck9a (test_plugins.test_preview.Test) ... ok
test_previewCheck9b (test_plugins.test_preview.Test) ... ok
test_rst (test_plugins.test_preview.Test) ... ok
test_settingUiCheck1 (test_plugins.test_preview.Test)
When Enki runs for the first time, the CodeChat module should be ... ok
test_settingUiCheck3 (test_plugins.test_preview.Test)
The Enable CodeChat checkbox should only be enabled if CodeChat can ... ok
test_settingUiCheck3a (test_plugins.test_preview.Test)
test_uiCheck1a has tested the case when Sphinx is disabled. This ... ok
test_ctrl_backspace_path (test_plugins.test_search.Gui) ... ok
test_esc_on_editor_closes (test_plugins.test_search.Gui) ... ok
test_esc_on_widget_closes (test_plugins.test_search.Gui) ... ok
test_highlight_found_items (test_plugins.test_search.InFile) ... ok
test_search_next (test_plugins.test_search.InFile) ... ok
test_search_previous (test_plugins.test_search.InFile) ... ok
test_select_and_search (test_plugins.test_search.InFile) ... ok
test_select_and_search_multiline (test_plugins.test_search.InFile) ... ok
test_type_and_search (test_plugins.test_search.InFile) ... ok
test_whole_word (test_plugins.test_search.InFile) ... ok
test_1 (test_plugins.test_search.ReplaceInDirectory) ... ok
test_1 (test_plugins.test_qpart_settings.AutoCompletion) ... ok
test_2 (test_plugins.test_qpart_settings.AutoCompletion) ... ok
test_1 (test_plugins.test_qpart_settings.Edge) ... ok
test_2 (test_plugins.test_qpart_settings.Edge) ... ok
test_3 (test_plugins.test_qpart_settings.Edge) ... ok
test_4 (test_plugins.test_qpart_settings.Edge) ... ok
test_1 (test_plugins.test_qpart_settings.Eol) ... ok
test_2 (test_plugins.test_qpart_settings.Eol) ... ok
test_3 (test_plugins.test_qpart_settings.Eol) ... ok
test_4 (test_plugins.test_qpart_settings.Eol) ... ok
test_1 (test_plugins.test_qpart_settings.Font) ... ok
test_1 (test_plugins.test_qpart_settings.Indent) ... ok
test_2 (test_plugins.test_qpart_settings.Indent) ... ok
test_1 (test_plugins.test_qpart_settings.WhiteSpaceVisibility) ... ok
test_1 (test_plugins.test_qpart_settings.WhitespaceStrip) ... ok
test_1 (test_plugins.test_qpart_settings.Wrap) ... ok
test_2 (test_plugins.test_qpart_settings.Wrap) ... ok
test_3 (test_plugins.test_qpart_settings.Wrap) ... ok
test_1 (test_plugins.test_approx_match.TestApproxMatch) ... ERROR
test_11 (test_plugins.test_approx_match.TestApproxMatch) ... expected failure
test_12 (test_plugins.test_approx_match.TestApproxMatch) ... expected failure
test_13 (test_plugins.test_approx_match.TestApproxMatch) ... ERROR
test_14 (test_plugins.test_approx_match.TestApproxMatch) ... ERROR
test_15 (test_plugins.test_approx_match.TestApproxMatch) ... ERROR
test_2 (test_plugins.test_approx_match.TestApproxMatch) ... ERROR
test_3 (test_plugins.test_approx_match.TestApproxMatch) ... ERROR
test_4 (test_plugins.test_approx_match.TestApproxMatch) ... ERROR
test_5 (test_plugins.test_approx_match.TestApproxMatch) ... ERROR
test_6 (test_plugins.test_approx_match.TestApproxMatch) ... ERROR
test_7 (test_plugins.test_approx_match.TestApproxMatch) ... ERROR
test_8 (test_plugins.test_approx_match.TestApproxMatch) ... ERROR
test_9 (test_plugins.test_approx_match.TestApproxMatch) ... ERROR
test_1 (test_plugins.test_approx_match.TestRefineSearchResult) ... ok
test_10 (test_plugins.test_approx_match.TestRefineSearchResult) ... skipped 'Long-running performance test'
test_11 (test_plugins.test_approx_match.TestRefineSearchResult) ... ok
test_12 (test_plugins.test_approx_match.TestRefineSearchResult) ... ok
test_13 (test_plugins.test_approx_match.TestRefineSearchResult) ... ok
test_14 (test_plugins.test_approx_match.TestRefineSearchResult) ... ok
test_15 (test_plugins.test_approx_match.TestRefineSearchResult) ... ok
test_16 (test_plugins.test_approx_match.TestRefineSearchResult) ... ok
test_2 (test_plugins.test_approx_match.TestRefineSearchResult) ... ok
test_3 (test_plugins.test_approx_match.TestRefineSearchResult) ... ok
test_4 (test_plugins.test_approx_match.TestRefineSearchResult) ... ok
test_5 (test_plugins.test_approx_match.TestRefineSearchResult) ... ok
test_6 (test_plugins.test_approx_match.TestRefineSearchResult) ... ok
test_7 (test_plugins.test_approx_match.TestRefineSearchResult) ... ok
test_8 (test_plugins.test_approx_match.TestRefineSearchResult) ... ok
test_9 (test_plugins.test_approx_match.TestRefineSearchResult) ... ok
test_1 (test_plugins.test_file_browser.Test)
Restore path ... ok
test_1 (test_plugins.test_navigator.Gui) ... ok
test_2 (test_plugins.test_navigator.Gui) ... ok
test_3 (test_plugins.test_navigator.Gui) ... ok
test_4 (test_plugins.test_navigator.Gui) ... ok
test_5 (test_plugins.test_navigator.Gui) ... ok
test_6 (test_plugins.test_navigator.Gui) ... ok
test_7 (test_plugins.test_navigator.Gui) ... ok
test_8 (test_plugins.test_navigator.Gui) ... ok
test_1 (test_plugins.test_navigator.Parser) ... ok
test_2 (test_plugins.test_navigator.Parser) ... ok
test_3 (test_plugins.test_navigator.Parser)
Ignore warning from ctags ... ok
test_1 (test_plugins.test_navigator.Settings) ... ok
test_2 (test_plugins.test_navigator.Settings)
Warning about etags ... ok
test_3 (test_plugins.test_navigator.Settings) ... ok
test_1 (test_plugins.test_repl.Test) ... skipped 'scheme command not found. Cannot run the test without it'
test_2 (test_plugins.test_repl.Test) ... ok
test_3 (test_plugins.test_repl.Test) ... ok
test_4 (test_plugins.test_repl.Test) ... ok
test_action_enabled (test_plugins.test_workspace_actions.Rename) ... ok
test_dev_null (test_plugins.test_workspace_actions.Rename) ... ok
test_dev_null_os_fail (test_plugins.test_workspace_actions.Rename) ... ok
test_os_fail (test_plugins.test_workspace_actions.Rename) ... ok
test_same_path (test_plugins.test_workspace_actions.Rename) ... ok
test_success (test_plugins.test_workspace_actions.Rename) ... ok
test_action_enabled (test_plugins.test_workspace_actions.ToggleExecutable) ... ok
test_action_text (test_plugins.test_workspace_actions.ToggleExecutable) ... ok
test_modify_flags (test_plugins.test_workspace_actions.ToggleExecutable) ... ok
test_os_fail (test_plugins.test_workspace_actions.ToggleExecutable) ... ok
test_1 (test_plugins.test_lint.Test)
File is checked after opened ... ok
test_2 (test_plugins.test_lint.Test)
_getPylintVersion ... ok
test_3 (test_plugins.test_lint.Test)
Settings ... ok
test_1 (test_lib.test_future.TestAsyncController) ... ok
test_10 (test_lib.test_future.TestAsyncController) ... ok
test_11 (test_lib.test_future.TestAsyncController) ... ok
test_12 (test_lib.test_future.TestAsyncController) ... ok
test_13 (test_lib.test_future.TestAsyncController) ... ok
test_14 (test_lib.test_future.TestAsyncController) ... ok
test_15 (test_lib.test_future.TestAsyncController) ... ok
test_2 (test_lib.test_future.TestAsyncController) ... ok
test_3 (test_lib.test_future.TestAsyncController) ... ok
test_4 (test_lib.test_future.TestAsyncController) ... ok
test_5 (test_lib.test_future.TestAsyncController) ... ok
test_6 (test_lib.test_future.TestAsyncController) ... ok
test_7 (test_lib.test_future.TestAsyncController) ... ok
test_8 (test_lib.test_future.TestAsyncController) ... ok
test_9 (test_lib.test_future.TestAsyncController) ... ok
test_1 (test_core.test_uisavefiles.Test) ... ok
test_2 (test_core.test_uisavefiles.Test) ... ok
test_3 (test_core.test_uisavefiles.Test) ... ok
test_4 (test_core.test_uisavefiles.Test) ... ok
test_5 (test_core.test_uisavefiles.Test) ... ok
test_6 (test_core.test_uisavefiles.Test) ... ok
test_1 (test_core.test_detect_language.Test) ... ok
test_2 (test_core.test_detect_language.Test) ... ok
test_3 (test_core.test_detect_language.Test) ... ok
test_4 (test_core.test_detect_language.Test) ... ok
test_5 (test_core.test_detect_language.Test) ... ok
test_dev_null (test_core.test_opened_files_dock.Rename) ... ok
test_dev_null_os_fail (test_core.test_opened_files_dock.Rename) ... ok
test_flags (test_core.test_opened_files_dock.Rename) ... ok
test_os_fail (test_core.test_opened_files_dock.Rename) ... ok
test_same_path (test_core.test_opened_files_dock.Rename) ... ok
test_success (test_core.test_opened_files_dock.Rename) ... ok
test_1 (test_core.test_open_file.OpenFail) ... ok
test_2 (test_core.test_open_file.OpenFail) ... ok
test_3 (test_core.test_open_file.OpenFail) ... ok
test_4 (test_core.test_open_file.OpenFail) ... ok
test_1 (test_core.test_open_file.Test) ... ok
test_1 (test_core.test_detect_eol.Test) ... ok
test_2 (test_core.test_detect_eol.Test) ... ok
test_3 (test_core.test_detect_eol.Test) ... ok
test_4 (test_core.test_detect_eol.Test) ... ok
test_5 (test_core.test_detect_eol.Test) ... ok
test_1 (test_core.test_filewatcher.Test) ... ok
test_2 (test_core.test_filewatcher.Test) ... ok
test_3 (test_core.test_filewatcher.Test) ... ok
test_4 (test_core.test_filewatcher.Test) ... ok
test_1 (test_core.test_hideall.Test) ... ok
test_1 (test_core.test_core.RestoreOldConfigs) ... ok
test_2 (test_core.test_core.RestoreOldConfigs) ... ok
test_dark_cmd (test_widgets.test_termwidget.Formatting) ... ok
test_dark_error (test_widgets.test_termwidget.Formatting) ... ok
test_dark_hint (test_widgets.test_termwidget.Formatting) ... ok
test_dark_out (test_widgets.test_termwidget.Formatting) ... ok
test_light_cmd (test_widgets.test_termwidget.Formatting) ... ok
test_light_error (test_widgets.test_termwidget.Formatting) ... ok
test_light_hint (test_widgets.test_termwidget.Formatting) ... ok
test_light_out (test_widgets.test_termwidget.Formatting) ... ok
test_1 (test_widgets.test_termwidget.History) ... ok
test_1 (test_widgets.test_termwidget.Lang) ... ok

======================================================================
ERROR: test_1 (test_plugins.test_approx_match.TestApproxMatch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andrei/code/enki/tests/test_plugins/test_approx_match.py", line 60, in test_1
    targetText = 'test')
  File "/home/andrei/code/enki/tests/../enki/plugins/preview/approx_match.py", line 203, in findApproxTextInTarget
    match, beginInTarget, endInTarget = findApproxText(searchText[begin:end], targetText)
TypeError: 'NoneType' object is not callable

======================================================================
ERROR: test_13 (test_plugins.test_approx_match.TestApproxMatch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andrei/code/enki/tests/test_plugins/test_approx_match.py", line 140, in test_13
    targetText = ' test    ')
  File "/home/andrei/code/enki/tests/../enki/plugins/preview/approx_match.py", line 203, in findApproxTextInTarget
    match, beginInTarget, endInTarget = findApproxText(searchText[begin:end], targetText)
TypeError: 'NoneType' object is not callable

======================================================================
ERROR: test_14 (test_plugins.test_approx_match.TestApproxMatch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andrei/code/enki/tests/test_plugins/test_approx_match.py", line 155, in test_14
    targetText = 'test')
  File "/home/andrei/code/enki/tests/../enki/plugins/preview/approx_match.py", line 203, in findApproxTextInTarget
    match, beginInTarget, endInTarget = findApproxText(searchText[begin:end], targetText)
TypeError: 'NoneType' object is not callable

======================================================================
ERROR: test_15 (test_plugins.test_approx_match.TestApproxMatch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andrei/code/enki/tests/test_plugins/test_approx_match.py", line 165, in test_15
    targetText = '\n\n\n\ntest\n\n\n\n')
  File "/home/andrei/code/enki/tests/../enki/plugins/preview/approx_match.py", line 203, in findApproxTextInTarget
    match, beginInTarget, endInTarget = findApproxText(searchText[begin:end], targetText)
TypeError: 'NoneType' object is not callable

======================================================================
ERROR: test_2 (test_plugins.test_approx_match.TestApproxMatch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andrei/code/enki/tests/test_plugins/test_approx_match.py", line 69, in test_2
    targetText = 'test')
  File "/home/andrei/code/enki/tests/../enki/plugins/preview/approx_match.py", line 203, in findApproxTextInTarget
    match, beginInTarget, endInTarget = findApproxText(searchText[begin:end], targetText)
TypeError: 'NoneType' object is not callable

======================================================================
ERROR: test_3 (test_plugins.test_approx_match.TestApproxMatch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andrei/code/enki/tests/test_plugins/test_approx_match.py", line 78, in test_3
    targetText = 'test')
  File "/home/andrei/code/enki/tests/../enki/plugins/preview/approx_match.py", line 203, in findApproxTextInTarget
    match, beginInTarget, endInTarget = findApproxText(searchText[begin:end], targetText)
TypeError: 'NoneType' object is not callable

======================================================================
ERROR: test_4 (test_plugins.test_approx_match.TestApproxMatch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andrei/code/enki/tests/test_plugins/test_approx_match.py", line 87, in test_4
    targetText = 'test\ntest')
  File "/home/andrei/code/enki/tests/../enki/plugins/preview/approx_match.py", line 203, in findApproxTextInTarget
    match, beginInTarget, endInTarget = findApproxText(searchText[begin:end], targetText)
TypeError: 'NoneType' object is not callable

======================================================================
ERROR: test_5 (test_plugins.test_approx_match.TestApproxMatch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andrei/code/enki/tests/test_plugins/test_approx_match.py", line 96, in test_5
    targetText = 'test\ntest')
  File "/home/andrei/code/enki/tests/../enki/plugins/preview/approx_match.py", line 203, in findApproxTextInTarget
    match, beginInTarget, endInTarget = findApproxText(searchText[begin:end], targetText)
TypeError: 'NoneType' object is not callable

======================================================================
ERROR: test_6 (test_plugins.test_approx_match.TestApproxMatch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andrei/code/enki/tests/test_plugins/test_approx_match.py", line 104, in test_6
    targetText = 'The CodeChat user manual gives a broad overview of this system. In contrast, this document discusses the implementation specifics of the CodeChat system.')
  File "/home/andrei/code/enki/tests/../enki/plugins/preview/approx_match.py", line 203, in findApproxTextInTarget
    match, beginInTarget, endInTarget = findApproxText(searchText[begin:end], targetText)
TypeError: 'NoneType' object is not callable

======================================================================
ERROR: test_7 (test_plugins.test_approx_match.TestApproxMatch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andrei/code/enki/tests/test_plugins/test_approx_match.py", line 113, in test_7
    targetText = 'bwxyzcd')
  File "/home/andrei/code/enki/tests/../enki/plugins/preview/approx_match.py", line 203, in findApproxTextInTarget
    match, beginInTarget, endInTarget = findApproxText(searchText[begin:end], targetText)
TypeError: 'NoneType' object is not callable

======================================================================
ERROR: test_8 (test_plugins.test_approx_match.TestApproxMatch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andrei/code/enki/tests/test_plugins/test_approx_match.py", line 122, in test_8
    targetText = 'bqwc?xyzaad')
  File "/home/andrei/code/enki/tests/../enki/plugins/preview/approx_match.py", line 203, in findApproxTextInTarget
    match, beginInTarget, endInTarget = findApproxText(searchText[begin:end], targetText)
TypeError: 'NoneType' object is not callable

======================================================================
ERROR: test_9 (test_plugins.test_approx_match.TestApproxMatch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andrei/code/enki/tests/test_plugins/test_approx_match.py", line 131, in test_9
    targetText = 'xxabcdabcdabcdxxx')
  File "/home/andrei/code/enki/tests/../enki/plugins/preview/approx_match.py", line 203, in findApproxTextInTarget
    match, beginInTarget, endInTarget = findApproxText(searchText[begin:end], targetText)
TypeError: 'NoneType' object is not callable

----------------------------------------------------------------------
Ran 272 tests in 57.923s

FAILED (errors=12, skipped=9, expected failures=3)

**Comment by bjones1** [comment]
I can't see to reproduce this. I'm running on enki head, Mint 16 32-bit. To install, I ran win/enki_install.sh. Is there any way you could send me your VirtualBox files?

The error confuses me -- it suggests that `findApproxText = None`, not that `findApproxText` is undefined (which would raise a NameError). I'm not sure how the code would get there, but any ideas on how to reproduce would be helpful.

**Comment by hlamer** [comment]
I've found that test_preview_sync.py test_sync23 breaks the approx match tests. Will try to understand why later.

**Comment by hlamer** [comment]
I've dropped the test, because this import magic looks too tricky for me. Tests are good, but not when they are so complicated. However if you've fixed it, I'll restore it.

**Comment by bjones1** [comment]
OK, if I find a better way to express this I'll rewrite.
